SHELL := /bin/bash
.PHONY: run format

format-all:
	@echo "Format using csharpier on a mac without hooks - install globally"
	dotnet csharpier .

run-build:
	@echo "Run quickly"
	dotnet build
	dotnet run
